name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Add COMMIT_ID env property with commit short sha
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> $GITHUB_ENV