name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Add COMMIT_ID env property with commit short sha
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jaysuzi5/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install argocd
        shell: bash
        run: |
          curl -ksSl -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: |
          # Login to argocd
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}

          # Add repo if not already added
          if ! argocd repo list | grep -q 'https://github.com/jaysuzi5-organization/${{values.app_name}}'; then
            argocd repo add 'https://github.com/jaysuzi5-organization/${{values.app_name}}.git'
          fi

          # Create the app only if it doesn't exist
          if ! argocd app get ${{values.app_name}} >/${{values.app_env}}/null 2>&1; then
            argocd app create ${{values.app_name}} \
              --repo https://github.com/jaysuzi5-organization/${{values.app_name}}.git \
              --path charts/${{values.app_name}} \
              --dest-namespace ${{values.app_env}} \
              --dest-server https://kubernetes.default.svc \
              --values values-${{values.app_env}}.yaml \
              --revision main \
              --sync-policy manual \
              --sync-option CreateNamespace=true
          else
            echo "App ${{values.app_name}} already exists."
          fi

          # Syncs the argocd app
          argocd app sync ${{values.app_name}}
          argocd app wait ${{values.app_name}} --timeout 180
