replicaCount: 1
image:
  repository: jaysuzi5/${{values.app_name}}
  pullPolicy: Always
  tag: latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5001
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: home.${{values.app_env}}.com
      paths:
        - path: /api/${{values.app_name}}/
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /api/${{values.app_name}}/v1/health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/${{values.app_name}}/v1/health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
otelEnv:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector-elastic.elasticsearch.svc.cluster.local:4318"
  - name: OTEL_EXPORTER_OTLP_PROTOCOL
    value: "http/protobuf"
  - name: OTEL_LOGS_EXPORTER
    value: "otlp"
  - name: OTEL_SERVICE_NAME
    value: "${{values.app_name}}"
  - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
    value: "true"
  - name: OTEL_LOG_LEVEL
    value: "debug"